"""initial schema

Revision ID: 892a4e7c24d0
Revises: 
Create Date: 2026-04-15 21:46:06.094253

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '892a4e7c24d0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approval_messages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('ix_group_telegram_id', 'group', ['telegram_id'], unique=False)
    op.create_index('ix_group_telegram_title', 'group', ['telegram_title'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'telegram_id', name='uix_group_telegram_id')
    )
    op.create_index('ix_player_telegram_first_name', 'player', ['telegram_first_name'], unique=False)
    op.create_index('ix_player_telegram_id', 'player', ['telegram_id'], unique=False)
    op.create_index('ix_player_telegram_username', 'player', ['telegram_username'], unique=False)
    op.create_table('draw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'draw_date', name='uix_group_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draw')
    op.drop_index('ix_player_telegram_username', table_name='player')
    op.drop_index('ix_player_telegram_id', table_name='player')
    op.drop_index('ix_player_telegram_first_name', table_name='player')
    op.drop_table('player')
    op.drop_index('ix_group_telegram_title', table_name='group')
    op.drop_index('ix_group_telegram_id', table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
